package com.fasty2b.youtube.entity;
// Generated May 20, 2018 2:51:41 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Token generated by hbm2java
 */
@Entity
@Table(name = "token", catalog = "youtube_db")
public class Token implements java.io.Serializable {

	private int id;
	private String channelId;
	private String accessToken;
	private String refreshToken;

	public Token() {
	}

	public Token(int id, String channelId) {
		this.id = id;
		this.channelId = channelId;
	}

	public Token(int id, String channelId, String accessToken, String refreshToken) {
		this.id = id;
		this.channelId = channelId;
		this.accessToken = accessToken;
		this.refreshToken = refreshToken;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "channel_id", nullable = false, length = 200)
	public String getChannelId() {
		return this.channelId;
	}

	public void setChannelId(String channelId) {
		this.channelId = channelId;
	}

	@Column(name = "access_token", length = 1000)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Column(name = "refresh_token", length = 1000)
	public String getRefreshToken() {
		return this.refreshToken;
	}

	public void setRefreshToken(String refreshToken) {
		this.refreshToken = refreshToken;
	}

}
