package com.fasty2b.youtube.entity;
// Generated May 20, 2018 2:51:41 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "youtube_db")
public class User implements java.io.Serializable {

	private String userId;
	private String userPass;
	private Integer userType;
	private Set<ChannelBasicInfo> channelBasicInfos = new HashSet<ChannelBasicInfo>(0);
	private Set<Channel> channels = new HashSet<Channel>(0);

	public User() {
	}

	public User(String userId, String userPass) {
		this.userId = userId;
		this.userPass = userPass;
	}

	public User(String userId, String userPass, Integer userType, Set<ChannelBasicInfo> channelBasicInfos,
			Set<Channel> channels) {
		this.userId = userId;
		this.userPass = userPass;
		this.userType = userType;
		this.channelBasicInfos = channelBasicInfos;
		this.channels = channels;
	}

	@Id

	@Column(name = "user_id", unique = true, nullable = false, length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "user_pass", nullable = false, length = 100)
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	@Column(name = "user_type")
	public Integer getUserType() {
		return this.userType;
	}

	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ChannelBasicInfo> getChannelBasicInfos() {
		return this.channelBasicInfos;
	}

	public void setChannelBasicInfos(Set<ChannelBasicInfo> channelBasicInfos) {
		this.channelBasicInfos = channelBasicInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Channel> getChannels() {
		return this.channels;
	}

	public void setChannels(Set<Channel> channels) {
		this.channels = channels;
	}

}
